### ISSUE TITLE
Error for long column-based lines

### ISSUE THREAD

**Issue by Terranigmus** [pyviz/datashader#722] opened 2019-03-08 09:58 UTC
## Description

Timeseries Example throws error in 
"Plotting large numbers of time series together " section

## Errors and warnings

TypeError                                 Traceback (most recent call last)
<ipython-input-21-d920cf076aec> in <module>
      1 cvs = ds.Canvas(plot_height=400, plot_width=1000)
----> 2 agg = cvs.line(df, x=time, y=list(range(points)), agg=ds.count(), axis=1)
      3 img = tf.shade(agg, how='eq_hist')
      4 img

TypeError: line() got an unexpected keyword argument 'axis'

## How to reproduce
Download the notebook: 

http://datashader.org/user_guide/3_Timeseries.html

execute all cells

## Your environment
Newest PyViz version, Anaconda 3 Python 3.7

**Comment by Terranigmus** [comment] 2019-03-08 10:04
I had a look in the documentation, according to the help of the cvs class, the line method does not support the axis argument. Where is this coming from?

**Comment by Terranigmus** [comment] 2019-03-08 12:08
Uh. This seems to be due to the Anaconda base environment using an older version of datashader and despite installing pyviz in the base environment, it refuses to use the newer version, mine is from 29th of January, seems like you udated inbetween. 
Anaconda issue.
Leaving open for people to see and notice

**Comment by Terranigmus** [comment] 2019-03-08 13:09
I changed my data around ait moreand there seems to be a maximum amount of columns that the code can take. 

Taking the example file at 
http://datashader.org/user_guide/3_Timeseries.html

Points=20 seems to be ok, 75 is the maximum amount of points I can give into the the code. 
76 crashes.

**Comment by jbednar** [comment] 2019-03-08 15:34
Sounds like you managed to get it to use the correct version, at least?  You can visit [status.pyviz.org](http://status.pyviz.org/) to see the latest versions of all PyViz packages across the various ways they can be obtained.

There shouldn't be any restriction on the number of columns; can you please provide a runnable example (e.g. defining `datac` in the code above)?

**Comment by Terranigmus** [comment] 2019-03-08 15:58
Ah sorry, that was me trying to adapt the example. 

i```
mport numpy as np
import pandas as pd
import datashader as ds
n = 100000
points = 76
time = np.linspace(0, 1, points)
data = np.cumsum(np.c_[np.zeros((n,1)), np.random.randn(n, points)] , axis=1)
data.shape
df = pd.DataFrame(data)
cvs = ds.Canvas(plot_height=400, plot_width=1000)
agg = cvs.line(df, x=time, y=list(range(points)), agg=ds.count(), axis=1)
img = tf.shade(agg, how='eq_hist')
img
```

**Comment by jbednar** [comment] 2019-03-08 20:16
Thanks for that example; I confirm I can reproduce the problem:

```
import numpy as np, pandas as pd, datashader as ds, datashader.transfer_functions as tf

def plot(points=50, n=10000):
    time = np.linspace(0.0, 1.0, points)
    data = np.cumsum(np.c_[np.zeros((n,1)), np.random.randn(n, points)] , axis=1)
    df   = pd.DataFrame(data)
    cvs  = ds.Canvas(plot_height=200, plot_width=600)
    agg  = cvs.line(df, x=time, y=list(range(points)), agg=ds.count(), axis=1)
    return tf.shade(agg, how='eq_hist')
```

![image](https://user-images.githubusercontent.com/1695496/54053297-6f5c2180-41ac-11e9-84c1-85658cc45d8c.png)

It looks like the issue is Numba related, because if I disable Numba it works fine:

```
diff --git a/datashader/spatial/hilbert_curve.py b/datashader/spatial/hilbert_curve.py
index 033b595..06161f5 100644
--- a/datashader/spatial/hilbert_curve.py
+++ b/datashader/spatial/hilbert_curve.py
@@ -10,6 +10,7 @@ for 2 dimensions with numba acceleration
 """
 
 NUMBA_DISABLE_JIT = os.environ.get('NUMBA_DISABLE_JIT', 0)
+NUMBA_DISABLE_JIT = 1
 
 
 @ngjit
diff --git a/datashader/utils.py b/datashader/utils.py
index fb660b1..878cd8d 100644
--- a/datashader/utils.py
+++ b/datashader/utils.py
@@ -18,6 +18,7 @@ except ImportError:
     RaggedDtype = type(None)
 
 ngjit = nb.jit(nopython=True, nogil=True)
+ngjit = lambda x, *args, **kw: x
 
 
 class Expr(object):
```
![image](https://user-images.githubusercontent.com/1695496/54053263-4f2c6280-41ac-11e9-9c25-cc4a6c997b29.png)

**Comment by jbednar** [comment] 2019-03-08 23:51
Luckily, it only seems to be a problem with the 0.42.0 Numba release, because it works fine with 0.41.0 and also with 0.43.0rc1, the latest dev release.  You can install the latest dev with `conda install -c numba numba`.  I think that means it will be fixed in the next full Numba release.

**Closed** 2019-03-08 23:52 UTC
