### ISSUE TITLE
shade function of datashader.transfer_functions does not implement 'span' parameter correctly.

### ISSUE THREAD

**Issue by xuanvinhilb** [pyviz/datashader#664] opened 2018-10-19 08:53 UTC
## Description
If we do not provide the span parameter, the function works correctly. For example:
    img = ds.transfer_functions.shade(agg, cmap=customColorMap, how='linear')
However, the function behaves incorrectly when the span parameter is provided. For example:
   img = ds.transfer_functions.shade(agg, cmap=customColorMap, how='linear', span = [valMin ,valMax])
This is because the data has been shifted with the offset = min(agg). However, the span value is not shifted accordingly. One way to fix it is to shift the span value
## suggested fix:
In the function _interpolate(),  we modify the function as follows:
CHANGE FROM:
if span is None:
        span = [np.nanmin(data), np.nanmax(data)]
    else:
        if how == 'eq_hist':
            # For eq_hist to work with span, we'll need to store the histogram
            # from the data and then apply it to the span argument.
            raise ValueError("span is not (yet) valid to use with eq_hist")
        span = interpolater(span,0)

TO:
if span is None:
        span = [np.nanmin(data), np.nanmax(data)]
    else:
        if how == 'eq_hist':
            # For eq_hist to work with span, we'll need to store the histogram
            # from the data and then apply it to the span argument.
            raise ValueError("span is not (yet) valid to use with eq_hist")
        if 'offset' in locals():
            span = interpolater(span - offset,0)
        else:
            span = interpolater(span,0)

**Comment by jbednar** [comment] 2018-10-19 17:57
Duplicate of https://github.com/pyviz/datashader/issues/368 . Can you try what is suggested there, and if it helps make a PR so that we can review this fix?

**Closed by jbednar** 2018-10-19 17:57 UTC

**Comment by xuanvinhilb** [comment] 2018-10-19 20:10
I read the thread 368 already. I did not check whether it fix my problem. However, what I suggested work for me.
